//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SceneViewer.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define ID_COLOR_EDITOR                 129
#define IDD_DIALOG1                     130
#define IDR_MFCTESTYPE                  131
#define IDR_ACCELERATOR1                133
#define IDD_DIALOG2                     134
#define IDB_BITMAP1                     139
#define IDB_BITMAP2                     141
#define IDD_LEFTDLG                     142
#define IDD_BOTTOMDLG                   144
#define IDB_BITMAP3                     145
#define IDB_BITMAP7                     149
#define IDB_BITMAP8                     150
#define IDB_BITMAP4                     151
#define IDD_BOTDLG                      153
#define IDD_DIALOG3                     155
#define IDD_DIALOG4                     156
#define IDD_DIALOG5                     157
#define IDD_DIALOG6                     158
#define COLOR_LUMSCROLL                 702
#define COLOR_HUE                       703
#define COLOR_SAT                       704
#define COLOR_LUM                       705
#define COLOR_RED                       706
#define COLOR_GREEN                     707
#define COLOR_BLUE                      708
#define COLOR_CURRENT                   709
#define COLOR_RAINBOW                   710
#define COLOR_SOLID                     713
#define COLOR_HUEACCEL                  723
#define COLOR_SATACCEL                  724
#define COLOR_LUMACCEL                  725
#define COLOR_REDACCEL                  726
#define COLOR_GREENACCEL                727
#define COLOR_BLUEACCEL                 728
#define COLOR_SOLID_LEFT                729
#define COLOR_SOLID_RIGHT               730
#define IDC_EDIT1                       1000
#define IDC_COMBO1                      1001
#define IDC_EDIT2                       1001
#define IDC_LIST1                       1002
#define IDC_DRAW                        1002
#define IDC_EDIT3                       1002
#define IDC_SCROLLBAR1                  1004
#define IDC_SCROLLBAR2                  1005
#define IDC_SCROLLBAR3                  1006
#define IDC_TWHL1                       1011
#define IDC_TWHL2                       1013
#define IDC_TWHL3                       1015
#define IDC_USER1                       1016
#define IDC_USER2                       1017
#define IDC_GENERIC1                    1018
#define IDC_CREATE_DIRECTIONALLIGHT     1019
#define IDC_CREATE_POINTLIGHT           1020
#define IDC_CREATE_SPOTLIGHT            1021
#define IDC_BUTTON4                     1024
#define ID_INVENTOR_EDIT_LIGHT_COLOR    1024
#define ID_INVENTOR_EDIT_LIGHT_ATTR     1024
#define IDC_LIGHT_ON                    2025
#define IDC_ICON_ON                     2026
#define IDC_DELETE_LIGHT                2027
#define IDC_LIGHT_LIST                  2028
#define INVENTOR_EDIT_BACKGROUND        32808
#define ID_INVENTOR_TRANSFOMER          32809
#define ID_INVENTOR_EDIT_PARENT         33778
#define ID_INVENTOR_EDIT_ALL            33779
#define INVENTOR_VIEW_PICK              33780
#define ID_INVENTOR_TRACKBALL           33781
#define ID_INVENTOR_HANDLEBOX           33782
#define ID_INVENTOR_JACK                33783
#define ID_INVENTOR_CENTERBALL          33784
#define ID_INVENTOR_XFBOX               33785
#define ID_INVENTOR_TABBOX              33786
#define ID_INVENTOR_NO_MANIPS           33787
#define INVENTOR_EDIT_XFORM             33788
#define INVENTOR_EDIT_LIGHT             33789
#define INVENTOR_EDIT_MATERIAL          33790
#define INVENTOR_EDIT_COLOR             33791
#define ID_LIGHTING_SPOTLIGHT           33792
#define ID_INVENTOR_TRANSFORMER         33792
#define ID_LIGHTING_DIRECTIONAL         33793
#define ID_LIGHTING_POINT               33794
#define ID_LIGHTING_AMBIENT             33795
#define IDC_INVENTOR_EXAMINER           33796
#define IDC_INVENTOR_WALK               33797
#define IDC_INVENTOR_FLY                33798
#define IDC_INVENTOR_PLANE              33799
#define ID_SELECTION_SINGLE             33800
#define ID_SELECTION_TOGGLE             33801
#define ID_SELECTION_SHIFT              33802
#define ID_CAMERATOOLBAR                33806
#define ID_THUMBWHEELBAR                33807
#define IDS_EXAMINER_TITLE              61204
#define IDS_FLY_TITLE                   61205
#define IDS_WALK_TITLE                  61206
#define IDS_PLANE_TITLE                 61207
#define IDS_UNTITLED                    61208

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        159
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1029
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
