// stdafx.h : include file for standard system include files,
//  or project specific include files that are used frequently, but
//      are changed infrequently
//

#include <afxwin.h>         // MFC core and standard components
#include <afxext.h>         // MFC extensions
#include <afxole.h>         // MFC OLE classes
#include <afxodlgs.h>       // MFC OLE dialog classes
#include <afxdisp.h>        // MFC OLE automation classes
#include "resource.h"
#include "SceneViewerDefinedMsgs.h"


// Inventor includes
#include /**/ <Inventor/SoDB.h>
#include /**/ <Inventor/SoInput.h>
#include /**/ <Inventor/SoInteraction.h>
#include /**/ <Inventor/nodekits/SoNodeKit.h>
#include /**/ <Inventor/nodes/SoCone.h>
#include /**/ <Inventor/nodes/SoDirectionalLight.h>
#include /**/ <Inventor/nodes/SoMaterial.h>
#include /**/ <Inventor/nodes/SoPerspectiveCamera.h>
#include /**/ <Inventor/nodes/SoSeparator.h>




